# Generated by Django 5.1 on 2024-08-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyConstituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booths.district')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voter_id', models.CharField(max_length=20, unique=True)),
                ('assembly_constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booths.assemblyconstituency')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booths.district')),
            ],
        ),
        migrations.CreateModel(
            name='VotingBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('assembly_constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booths.assemblyconstituency')),
            ],
        ),
    ]
