# Generated by Django 5.1 on 2024-08-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voting_booth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booths.votingbooth'),
            preserve_default=False,
        ),
    ]
